apiVersion: v1
kind: Service
metadata:
  name: shop-service
spec:
  selector:
    app: shop-app
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 5001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-app
spec:
  selector:
    matchLabels:
      app: shop-app
  replicas: 1
  template:
    metadata:
      labels:
        app: shop-app
    spec:
      containers:
        - name: shop-app
          image: aksourav/micro_shop:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: shop-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-config
data:
  SQLALCHEMY_DATABASE_URI: "sqlite:///shop.db"
  AUTH_SERVICE_HOST: "auth-service.default"
  JWT_SECRET_KEY: "very_secret_key"
