apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  selector:
    matchLabels:
      app: auth-app
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth-app
          image: aksourav/micro_auth:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  SQLALCHEMY_DATABASE_URI: "sqlite:///users.db"
  JWT_SECRET_KEY: "very_secret_key"
